config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home'
  get 'projects', to: 'pages#projects'
  get 'contact', to: 'pages#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <div class="container">
  <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'Mi Portafolio', '/', class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Home", home_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Proyectos", projects_path, class: "nav-link" %>        
        </li>
        <li class="nav-item">
          <%= link_to "Contacto", contact_path, class: "nav-link" %>
        </li>
           </ul>
    </div>
  </div>
</nav>
    <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/contact.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col">
      <div class="card" style="width: 18rem;">
         <%= image_tag '1.png', class: 'card-img-top', alt: 'AlexLabbe' %>
        <div class="card-body">
          <h5 class="card-title">Contáctame</h5>
          <p class="card-text">Si tienes alguna pregunta o deseas ponerte en contacto, no dudes en enviarme un mensaje. Estoy aquí para ayudarte.</p>
          <a href="https://wa.me/+56930756419" class="btn btn-primary">Enviar Mensaje</a>
        </div>
      </div>
    </div>
  </div>
</div>
    

app/views/pages/home.html.erb
    <div class="container text-center mt-5">
    <div class="card mx-auto" style="width: 18rem;">
    <%= image_tag '1.png', class: 'card-img-top', alt: 'Alex Labbé Rodríguez' %>
    <div class="card-body">
    </div>
  </div>
      <h1>Alex Labbé Rodríguez</h1>
      <h2 class="mt-3 mb-4">Portafolio</h2>
      <h5 class="mb-4">Esta página muestra tres proyectos de desarrollo web, utilizando HTML, CSS y JavaScript.</h5>
      <h6 class="mb-4">Se utilizaron Bootstrap y estilos personalizados. Estos proyectos fueron realizados en el marco de los desafíos del Bootcamp Ruby on Rails para Startups.</h6>
      <p class="mb-5">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <a href="<%= url_for(controller: 'pages', action: 'projects') %>" class="btn btn-primary">Ver Proyectos</a>
    
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

app/views/pages/projects.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col">
    <div class="card" style="width: 18rem;">
    <%= image_tag 'IguanaPage.png', class: 'card-img-top', alt: 'IguanaPage' %>
    <div class="card-body">
      <h5 class="card-title">Proyecto Iguana Page</h5>
      <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      <a href="https://7aleobe7labrod7.github.io/IguanaPage/" class="btn btn-primary">Ver más</a>
    </div>
  </div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem;">
        <%= image_tag 'CupponWeb.png', class: 'card-img-top', alt: 'CupponPage' %>
  <div class="card-body">
    <h5 class="card-title">Proyecto Cuppon</h5>
    <p class="card-text">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
    <a href="https://7aleobe7labrod7.github.io/CupponPage/" class="btn btn-primary">Ver más</a>
  </div>
</div>
    </div>
    <div class="col">
    <div class="card" style="width: 18rem;">
    <%= image_tag 'RicomidaPage.png', class: 'card-img-top', alt: 'RicomidaPage' %>
    <div class="card-body">
      <h5 class="card-title">Proyecto Ricomida</h5>
      <p class="card-text">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora.</p>
      <a href="https://4lexlabb3.github.io/DesafioRicomida/" class="btn btn-primary">Ver más</a>
    </div>
  </div>
    </div>
  </div>
</div>